#!/usr/bin/env bash

# Transfers a file from client to a server.

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ];
    then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

else
    path_to_file=$1
    ip=$2
    username=$3
    path_to_ssh_key=$4
    #echo "$path_to_file, $ip, $username, $path_to_ssh_key"
fi

scp -ib $path_to_ssh_key $path_to_file $username@$ip
