#!/usr/bin/env bash
#pings an IP address passed as an argument.
if [ $# == "" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    for _ in 1 2 3 4 5
    do
	ping "$1"
    done
fi
