#!/usr/bin/env bash
#pings an IP address passed as an argument.
if [ $# == 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    for i in 1 2 3 4 5
    do
	ping $1
    done
fi
