#!/usr/bin/env bash

# Fixes a bug: Nginx installation not listening on port 80
sudo apt-get install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo iptables -F
sudo iptables -X
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t mangle -F
sudo iptables -t mangle -X
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT
