#!/usr/bin/env bash
#script taht creates a file, displays to infinity and beyond indefinitely
#diplays I hate the kill command when receiving a SIGTERM signal
#Deletes the file created and terminaes itself  when receiving a SIGQUIT or
#SIGTERM signal

sudo touch /var/run/holbertonscript.pid
sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'
while True
do
echo "To infinity and beyond"
sleep 2
trap 'echo"I hate the kill command"; sudo rm var/run/holbertonscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
done
