#!/usr/bin/env bash
# Configures an ubuntu server to :
#                               localhost resolves to 127.0.0.1
#                               facebook.com resolves to 8.8.8.8
# sed syntax: s/regexp/replacement/
# Adding before line 1 syntax: sed -i '1 i\anything' file_path
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.new
sed -i 's/.*facebook.com//g' ~/hosts.new
sed -i '1 i\8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
