#!/usr/bin/env bash
# Debugging Apache to run and display the message Hello Holberton
# Read: https://askubuntu.com/questions/256013/apache-error-could-not-reliably-
# determine-the-servers-fully-qualified-domain-n
service apache2 start
